# Autogenerated config.py
#
# NOTE: config.py is intended for advanced users who are comfortable
# with manually migrating the config file on qutebrowser upgrades. If
# you prefer, you can also configure qutebrowser using the
# :set/:bind/:config-* commands without having to write a config.py
# file.
#
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Change the argument to True to still load settings configured via autoconfig.yml
config.load_autoconfig(False)

# Which cookies to accept. With QtWebEngine, this setting also controls
# other features with tracking capabilities similar to those of cookies;
# including IndexedDB, DOM storage, filesystem API, service workers, and
# AppCache. Note that with QtWebKit, only `all` and `never` are
# supported as per-domain values. Setting `no-3rdparty` or `no-
# unknown-3rdparty` per-domain on QtWebKit will have the same effect as
# `all`. If this setting is used with URL patterns, the pattern gets
# applied to the origin/first party URL of the page making the request,
# not the request URL. With QtWebEngine 5.15.0+, paths will be stripped
# from URLs, so URL patterns using paths will not match. With
# QtWebEngine 5.15.2+, subdomains are additionally stripped as well, so
# you will typically need to set this setting for `example.com` when the
# cookie is set on `somesubdomain.example.com` for it to work properly.
# To debug issues with this setting, start qutebrowser with `--debug
# --logfilter network --debug-flag log-cookies` which will show all
# cookies being set.
# Type: String
# Valid values:
#   - all: Accept all cookies.
#   - no-3rdparty: Accept cookies from the same origin only. This is known to break some sites, such as GMail.
#   - no-unknown-3rdparty: Accept cookies from the same origin only, unless a cookie is already set for the domain. On QtWebEngine, this is the same as no-3rdparty.
#   - never: Don't accept cookies at all.
config.set('content.cookies.accept', 'all', 'chrome-devtools://*')

# Which cookies to accept. With QtWebEngine, this setting also controls
# other features with tracking capabilities similar to those of cookies;
# including IndexedDB, DOM storage, filesystem API, service workers, and
# AppCache. Note that with QtWebKit, only `all` and `never` are
# supported as per-domain values. Setting `no-3rdparty` or `no-
# unknown-3rdparty` per-domain on QtWebKit will have the same effect as
# `all`. If this setting is used with URL patterns, the pattern gets
# applied to the origin/first party URL of the page making the request,
# not the request URL. With QtWebEngine 5.15.0+, paths will be stripped
# from URLs, so URL patterns using paths will not match. With
# QtWebEngine 5.15.2+, subdomains are additionally stripped as well, so
# you will typically need to set this setting for `example.com` when the
# cookie is set on `somesubdomain.example.com` for it to work properly.
# To debug issues with this setting, start qutebrowser with `--debug
# --logfilter network --debug-flag log-cookies` which will show all
# cookies being set.
# Type: String
# Valid values:
#   - all: Accept all cookies.
#   - no-3rdparty: Accept cookies from the same origin only. This is known to break some sites, such as GMail.
#   - no-unknown-3rdparty: Accept cookies from the same origin only, unless a cookie is already set for the domain. On QtWebEngine, this is the same as no-3rdparty.
#   - never: Don't accept cookies at all.
config.set('content.cookies.accept', 'all', 'devtools://*')

# Value to send in the `Accept-Language` header. Note that the value
# read from JavaScript is always the global value.
# Type: String
config.set('content.headers.accept_language', '', 'https://matchmaker.krunker.io/*')

# User agent to send.  The following placeholders are defined:  *
# `{os_info}`: Something like "X11; Linux x86_64". * `{webkit_version}`:
# The underlying WebKit version (set to a fixed value   with
# QtWebEngine). * `{qt_key}`: "Qt" for QtWebKit, "QtWebEngine" for
# QtWebEngine. * `{qt_version}`: The underlying Qt version. *
# `{upstream_browser_key}`: "Version" for QtWebKit, "Chrome" for
# QtWebEngine. * `{upstream_browser_version}`: The corresponding
# Safari/Chrome version. * `{qutebrowser_version}`: The currently
# running qutebrowser version.  The default value is equal to the
# unchanged user agent of QtWebKit/QtWebEngine.  Note that the value
# read from JavaScript is always the global value. With QtWebEngine
# between 5.12 and 5.14 (inclusive), changing the value exposed to
# JavaScript requires a restart.
# Type: FormatString
config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}) AppleWebKit/{webkit_version} (KHTML, like Gecko) {upstream_browser_key}/{upstream_browser_version} Safari/{webkit_version}', 'https://web.whatsapp.com/')

# User agent to send.  The following placeholders are defined:  *
# `{os_info}`: Something like "X11; Linux x86_64". * `{webkit_version}`:
# The underlying WebKit version (set to a fixed value   with
# QtWebEngine). * `{qt_key}`: "Qt" for QtWebKit, "QtWebEngine" for
# QtWebEngine. * `{qt_version}`: The underlying Qt version. *
# `{upstream_browser_key}`: "Version" for QtWebKit, "Chrome" for
# QtWebEngine. * `{upstream_browser_version}`: The corresponding
# Safari/Chrome version. * `{qutebrowser_version}`: The currently
# running qutebrowser version.  The default value is equal to the
# unchanged user agent of QtWebKit/QtWebEngine.  Note that the value
# read from JavaScript is always the global value. With QtWebEngine
# between 5.12 and 5.14 (inclusive), changing the value exposed to
# JavaScript requires a restart.
# Type: FormatString
config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}; rv:90.0) Gecko/20100101 Firefox/90.0', 'https://accounts.google.com/*')

# User agent to send.  The following placeholders are defined:  *
# `{os_info}`: Something like "X11; Linux x86_64". * `{webkit_version}`:
# The underlying WebKit version (set to a fixed value   with
# QtWebEngine). * `{qt_key}`: "Qt" for QtWebKit, "QtWebEngine" for
# QtWebEngine. * `{qt_version}`: The underlying Qt version. *
# `{upstream_browser_key}`: "Version" for QtWebKit, "Chrome" for
# QtWebEngine. * `{upstream_browser_version}`: The corresponding
# Safari/Chrome version. * `{qutebrowser_version}`: The currently
# running qutebrowser version.  The default value is equal to the
# unchanged user agent of QtWebKit/QtWebEngine.  Note that the value
# read from JavaScript is always the global value. With QtWebEngine
# between 5.12 and 5.14 (inclusive), changing the value exposed to
# JavaScript requires a restart.
# Type: FormatString
config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99 Safari/537.36', 'https://*.slack.com/*')

# Load images automatically in web pages.
# Type: Bool
config.set('content.images', True, 'chrome-devtools://*')

# Load images automatically in web pages.
# Type: Bool
config.set('content.images', True, 'devtools://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome-devtools://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'devtools://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# editor
config.set('editor.command', ["st", "nvim", "-f", "{file}", "-c", ":call cursor({line},{column})"])
# file selector
config.set('fileselect.handler', 'external')
# folder select (xterm ranger)
# config.set('fileselect.folder.command', ["xterm", "-fa", "JetBrainsMonoMedium Nerd Font", "-fs", "9", "-geometry", "120x30+600+300", "-e", "ranger", "--choosedir={}"])
# file select single (xterm ranger)
# config.set('fileselect.single_file.command', ["xterm", "-fa", "JetBrainsMonoMedium Nerd Font", "-fs", "9", "-geometry", "120x30+600+300", "-e", "ranger", "--choosefile={}"])
# file select multiple (xterm ranger)
# config.set('fileselect.multiple_files.command', ["xterm", "-fa", "JetBrainsMonoMedium Nerd Font", "-fs", "9", "-geometry", "120x30+600+300", "-e", "ranger", "--choosefiles={}"])
# folder select (st lf)
config.set('fileselect.folder.command', ["st", "-n", "fcen", "-g", "120x30", "-e", "lfrun", "-last-dir-path={}"])
# file select single (st lf)
config.set('fileselect.single_file.command', ["st", "-n", "fcen", "-g", "120x30", "-e", "lfrun", "-selection-path={}"])
# file select multiple (st lf)
config.set('fileselect.multiple_files.command', ["st", "-n", "fcen", "-g", "120x30", "-e", "lfrun", "-selection-path={}"])

#fonts
config.set('fonts.default_family', 'JetBrainsMono Nerd Font')
config.set('fonts.default_size', '9pt')

# Default zoom
config.set('zoom.default', "100%")

# Start page
config.set('url.start_pages', 'https://start.duckduckgo.com')

# focus next
config.set('tabs.select_on_remove', 'last-used')

# Color settings

# # completion odd bg
# config.set('colors.completion.odd.bg', '#45475a')
# # completion evenbg
# config.set('colors.completion.even.bg', '#585b70')
# # completion select
# config.set('colors.completion.item.selected.bg', '#89b4fa')
# # conpletion category
# config.set('colors.completion.category.bg', '#1e1e2e')
# config.set('colors.completion.category.fg', '#cdd6fa')
# config.set('colors.completion.fg', '#cdd6fa')
# config.set('colors.completion.item.selected.border.bottom', '#89b4fa')
# config.set('colors.completion.item.selected.border.top', '#89b4fa')
# #  config.set('colors.completion.category.bg', 'qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #888888, stop:1 #505050)')
# # tabs odd bg
# config.set('colors.tabs.odd.bg', '#1e1e2e')
# # tabs odd selected bg/fg
# config.set('colors.tabs.selected.odd.bg', '#89b4fa')
# config.set('colors.tabs.selected.odd.fg', '#3B4252')
# # tabs even bg
# config.set('colors.tabs.even.bg', '#1e1e2e')
# # tabs even selected bg/fg
# config.set('colors.tabs.selected.even.bg', '#89b4fa')
# config.set('colors.tabs.selected.even.fg', '#3B4252')
# # red indicator
# config.set('colors.tabs.indicator.error', '#f38ba8')
# # blue indicator
# config.set('colors.tabs.indicator.start', '#89b4fa')
# # green indicator
# config.set('colors.tabs.indicator.stop', '#a6e3a1')
# # statusbar bg
# config.set('colors.statusbar.command.bg', '#1e1e2e')
# # statusbar caret
# config.set('colors.statusbar.caret.bg', '#94e2d5')
# # statusbar insert
# config.set('colors.statusbar.insert.bg', '#a6e3a1')
# # statusbar normal
# config.set('colors.statusbar.normal.bg', '#1e1e2e')
# # statusbar passthrough
# config.set('colors.statusbar.passthrough.bg', '#89b4fa')
# # status url fg
# config.set('colors.statusbar.url.success.https.fg', '#a6e3a1')
# # status hover url fg
# config.set('colors.statusbar.url.hover.fg', '#89b4fa')

# Completion bar settings

# Height
config.set('completion.height', '35%')
# Completion list order
config.set('completion.open_categories', ["bookmarks", "quickmarks", "history", "searchengines", "filesystem"])
# Scrollbar (off)
config.set('completion.scrollbar.width', 0)
# CMD history list size
config.set('completion.cmd_history_max_items', 20)
# Web history list size
config.set('completion.web_history.max_items', 50)

# Access Clipboard
config.set('content.javascript.can_access_clipboard', True)

# view PDF from web
config.set('content.pdfjs', True)

# Wait for download to disappear
config.set('downloads.remove_finished', 20000)

# Keyhint delay
config.set('keyhint.delay', 0)

# Spell check
config.set('spellcheck.languages', ["en-US"])

# Hint key
config.set('hints.chars', 'asdfjkl')

# Bindings for normal mode
config.bind('z', 'hint links spawn mpv {hint-url}')
config.bind('xb', 'config-cycle statusbar.show never always ')
config.bind('xt', 'config-cycle tabs.show never always')
config.bind('xx', 'config-cycle statusbar.show never always;;config-cycle tabs.show never always')
config.bind('gD', 'set-cmd-text -s :tab-give ')

config.set('content.fullscreen.window', False)
config.set('content.autoplay', False)

# config.set('hints.find_implementation', 'javascript')

# remove scroll to tabchangeDetails
config.set('tabs.mousewheel_switching', False)

config.set('downloads.location.directory', '/home/john/')
config.set('colors.webpage.darkmode.enabled', True)
config.set('content.cookies.accept', 'no-3rdparty')
config.set('content.user_stylesheets', '/home/john/.config/qutebrowser/quteuser.css')

import catppuccin

catppuccin.setup(c, 'mocha')
