#!/bin/sh

cat ~/.cache/brightness | sudo tee /sys/class/backlight/*/brightness
picom -b &
# for pipewire
pipewire &
pipewire-pulse &
wireplumber &
# for pulseaudio
# pulseaudio --start --log-target=syslog &
fcitx5 &
clipmenud  &
dunst &
unclutter --start-hidden --timeout 2 -f &
xrdb merge ~/.config/x11/Xresources_catppuccin &
feh --bg-fill --no-fehbg ~/personal/pictures/wall.png &
sudo keyd &

# run bar script and dwm ( do not remove this )
~/workspace/suckless/dwm/scripts/bar.sh &
dwm
